name: PR build

on: [pull_request]

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        run: |
          sleep 5s
      - name: Generate CodeCov Report Try 1
        if: github.event_name == 'pull_request'
        id: uploadReport1
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          fail_ci_if_error: true
      - name: Wait after upload failure
        if: steps.uploadReport1.outcome == 'failure'
        run: |
          sleep 10s
      - name: Generate CodeCov Report Try 2
        if: steps.uploadReport1.outcome == 'failure'
        id: uploadReport2
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          fail_ci_if_error: true
      - name: Wait after upload failure
        if: steps.uploadReport2.outcome == 'failure'
        run: |
          sleep 10s
      - name: Generate CodeCov Report Try 3
        if: steps.uploadReport2.outcome == 'failure'
        uses: codecov/codecov-action@v2
