name: Process load test results
on:
  repository_dispatch:
    types: [grpc-load-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prints payload
        run: |
          echo ${{ github.event.client_payload.status }}
          results="${{ github.event.client_payload.result }}"
          echo $results
          echo ${{ github.event.client_payload.errorRate }}
      - name: Process results
        if: ${{ github.event.client_payload.status == 'success' }}
        run: |
          git config --global user.email "dilansachinthanos@gmail.com"
          git config --global user.name "dilanSachi"
          branch_name="load-test-results"
          test_scenario="${{ github.event.client_payload.name }}"
          git checkout -b $branch_name
          git fetch
          git pull origin $branch_name
          echo ${{ github.event.client_payload.result }} >> song_lyric_crawler/$test_scenario/results/summary.csv
          git add song_lyric_crawler/$test_scenario/results/summary.csv
          git commit -m "Update $test_scenario test results on $(date)"
          git push origin "${branch_name}"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Check for existing PRs
        id: checkPRs
        shell: bash
        run: printf "::set-output name=prNotExists::%s" $(gh pr list --json headRefName --jq 'isempty(.[]| .headRefName | match("load-test-results"))')
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Create pull request for new summary
        if: ${{ steps.checkPRs.outputs.prNotExists == 'true' }}
        run: gh pr create --title "[Automated] Update summary csv files" --body "Update summary csv files"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Fail workflow
        if: ${{ github.event.client_payload.status != 'success' }}
        run: |
          echo "Load test "${{ github.event.client_payload.name }}" failed with status: "${{ github.event.client_payload.status }} "and error rate: "${{ github.event.client_payload.errorRate }}
          exit 1
