name: Process load test results
on:
  repository_dispatch:
    types: [grpc-load-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prints payload
        run: |
          results='${{ toJson(github.event.client_payload.results) }}'
          echo $results | jq
      - name: Process array
        run: |
          results='${{ toJson(github.event.client_payload.results) }}'
      - name: Process results
        run: |
          git config --global user.email "dilansachinthanos@gmail.com"
          git config --global user.name "dilanSachi"
          branch_name="load-test-results"
          git pull
          git checkout $branch_name || git checkout -b $branch_name
          echo '${{ toJson(github.event.client_payload.results) }}' | jq -c '.[]' |
          while ss=$"\n" read -r result; do
            host=$(echo "$result" | jq -r '.status');
            if [[ $host == "success" ]]
            then
              echo $(echo "$result" | jq -r '.result')
              test_scenario=$(echo "$result" | jq -r '.name')
              echo $(echo "$result" | jq -r '.result') >> song_lyric_crawler/$test_scenario/results/summary.csv
              git add song_lyric_crawler/$test_scenario/results/summary.csv
              git commit -m "Update $test_scenario test results on $(date)"
            else
              echo $(echo "$result" | jq -r '.errorRate')
            fi
          done
          git push origin "${branch_name}"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Create pull request for new summary
        if: ${{ github.event.client_payload.status == 'success' }}
        run: gh pr create --title "[Automated] Update summary csv files" --body "Update summary csv files"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Approve PR
        if: ${{ github.event.client_payload.status == 'success' }}
        run: gh pr review --approve
        env:
          GITHUB_TOKEN: ${{ secrets.S_PAT }}
      - name: Merge PR
        if: ${{ github.event.client_payload.status == 'success' }}
        run: |
          status="NOT COMPLETED"
          while [ ! -z "$status" ]
          do
            sleep 20
            status=$(gh pr status --jq '.currentBranch .statusCheckRollup[] | select(.status!="COMPLETED") | select(.context!="license/cla")' --json statusCheckRollup)
          done
          sleep 20
          gh pr merge --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Fail workflow
        if: ${{ github.event.client_payload.status != 'success' }}
        run: |
          echo "Load test "${{ github.event.client_payload.name }}" failed with status: "${{ github.event.client_payload.status }} "and error rate: "${{ github.event.client_payload.errorRate }}
          exit 1
